#!/bin/bash
# install-global.sh
# Installs the ambient skill system on this machine.
#
# Design: ONE canonical clone of ambient-library lives at $AMBIENT_HOME.
# Everything else just points into it — nothing is duplicated.
#
#   $AMBIENT_HOME/                  the single source of truth (full git clone)
#   ~/.claude/skills/ambient/SKILL.md   thin pointer → instructions in the clone
#   ~/.zshrc                       exports AMBIENT_HOME (for shell scripts)
#   ~/.claude/CLAUDE.md            records AMBIENT_HOME (for Claude's context)
#
# Updating the system is just `git -C $AMBIENT_HOME pull`. Re-run this script
# anytime — every write is an idempotent managed block.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/coachlou/ambient-library/main/install-global.sh | bash
#   AMBIENT_HOME=/custom/path bash install-global.sh   # override location

set -e

REPO="https://github.com/coachlou/ambient-library.git"

# --- Resolve AMBIENT_HOME -------------------------------------------------
# Precedence: existing env var → default. The default has no spaces so it is
# safe in YAML frontmatter and shell paths.
AMBIENT_HOME="${AMBIENT_HOME:-$HOME/ambient-library}"

CLAUDE_DIR="$HOME/.claude"
POINTER_DIR="$CLAUDE_DIR/skills/ambient"
ZSHRC="$HOME/.zshrc"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"

BEGIN="# >>> ambient-library >>>"
END="# <<< ambient-library <<<"
MD_BEGIN="<!-- >>> ambient-library >>> -->"
MD_END="<!-- <<< ambient-library <<< -->"

echo ""
echo "🌐 Installing ambient skill system..."
echo "   AMBIENT_HOME = $AMBIENT_HOME"
echo ""

# --- 1. Clone or update the canonical library -----------------------------
if [ -d "$AMBIENT_HOME/.git" ]; then
  echo "  ↻ Updating existing library..."
  git -C "$AMBIENT_HOME" pull --ff-only --quiet
else
  echo "  ⬇ Cloning library..."
  git clone --quiet "$REPO" "$AMBIENT_HOME"
fi

# --- 2. Write the thin pointer SKILL.md -----------------------------------
# Copy the canonical frontmatter, rewrite instructions_path to an absolute
# path into the clone, and append a body so Claude reads the right file even
# if the loader does not auto-follow instructions_path.
mkdir -p "$POINTER_DIR"
cp "$AMBIENT_HOME/ambient/SKILL.md" "$POINTER_DIR/SKILL.md"
# Rewrite the instructions_path line (| delimiter — path contains slashes).
sed -i.bak "s|^instructions_path:.*|instructions_path: $AMBIENT_HOME/ambient/instructions.md|" "$POINTER_DIR/SKILL.md"
rm -f "$POINTER_DIR/SKILL.md.bak"
cat >> "$POINTER_DIR/SKILL.md" <<EOF

<!-- Generated pointer. Do not edit — regenerated by install-global.sh. -->

This skill's full instructions live in the canonical ambient-library:

**$AMBIENT_HOME/ambient/instructions.md**

Read and follow that file. Resolve every relative reference inside it
(\`subskills/\`, etc.) from **$AMBIENT_HOME/ambient/**. The library root
\`AMBIENT_HOME\` is **$AMBIENT_HOME**.
EOF
echo "  ✓ Pointer: $POINTER_DIR/SKILL.md"

# --- helpers: idempotent managed blocks -----------------------------------
strip_block() {
  # strip_block <file> <begin-marker> <end-marker>  → prints file without block
  [ -f "$1" ] || return 0
  awk -v b="$2" -v e="$3" '
    index($0,b){skip=1}
    !skip{print}
    index($0,e){skip=0; next}
  ' "$1"
}

# --- 3. Export AMBIENT_HOME in ~/.zshrc -----------------------------------
touch "$ZSHRC"
{
  strip_block "$ZSHRC" "$BEGIN" "$END"
  echo "$BEGIN"
  echo "export AMBIENT_HOME=\"$AMBIENT_HOME\""
  echo "$END"
} > "$ZSHRC.tmp"
mv "$ZSHRC.tmp" "$ZSHRC"
echo "  ✓ Exported AMBIENT_HOME in ~/.zshrc"

# --- 4. Record AMBIENT_HOME in ~/.claude/CLAUDE.md ------------------------
mkdir -p "$CLAUDE_DIR"
touch "$CLAUDE_MD"
{
  strip_block "$CLAUDE_MD" "$MD_BEGIN" "$MD_END"
  echo "$MD_BEGIN"
  echo "## Ambient Library"
  echo "The ambient-library skill system is installed on this machine."
  echo "Its canonical location (AMBIENT_HOME) is: \`$AMBIENT_HOME\`"
  echo "When running ambient skills, resolve all file references from this path."
  echo "$MD_END"
} > "$CLAUDE_MD.tmp"
mv "$CLAUDE_MD.tmp" "$CLAUDE_MD"
echo "  ✓ Recorded AMBIENT_HOME in ~/.claude/CLAUDE.md"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Ambient skill is ready."
echo ""
echo "Open any project in Claude Code and say:"
echo "  \"Set up ambient-library in this project\""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
