#!/usr/bin/env python3
"""Expose a project's enabled domain skills to the harness's native skill listing.

Reads `domain_skills` from <project>/skills-manifest.yaml and writes a stub
SKILL.md for each enabled skill into the project's native skill directories:

  .claude/skills/<name>/SKILL.md   (Claude Code)
  .agents/skills/<name>/SKILL.md   (Codex and other Agent Skills harnesses)

A stub is the library skill's own frontmatter (so the harness lists it with the
same trigger) plus one line pointing at the library's instructions.md. Plain
files, not symlinks: symlinks need Developer Mode on Windows and rarely survive
zip/copy (ARCHITECTURE.md, "Why a routing table...").

The manifest stays the source of truth: stubs carrying MARKER whose name is no
longer enabled are removed, and every run rewrites stale ones (re-run after a
library update). Folders without MARKER (the user's own skills) are never touched.
Stubs hold an absolute path, so gitignore them in a shared repo.

  sync-skill-stubs.py [--project DIR] [--user] [--dry-run]

--user syncs ~/.aai/skills-manifest.yaml into ~/.claude/skills and ~/.agents/skills.
Prints one JSON object {"written", "removed", "missing", "skipped"}.
Exit 0 = done, 1 = error.
"""

import argparse
import json
import os
import re

# ROOT is wherever this copy lives: the plugin install folder, ~/.ailib, or a
# vendored .ailib/. Stubs point there, so re-run after the copy moves (a plugin
# update changes the versioned path).
ROOT = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))
LIBRARY = os.path.join(ROOT, "library")
TARGETS = (".claude/skills", ".agents/skills")
MARKER = "<!-- generated by ambient sync-skill-stubs.py; do not edit -->"


def enabled(manifest):
    """`domain_skills` names from the manifest: block list or flow `[a, b]`.

    Self-contained (no resolve.py) because the shipped plugin carries only this
    script, and it must run from a vendored .ailib/ too."""
    if not os.path.exists(manifest):
        return []
    lines = open(manifest, encoding="utf-8").read().splitlines()
    names, inside = [], False
    for raw in lines:
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        m = re.match(r"^domain_skills:\s*(.*)$", line)
        if m:
            inside = True
            if m.group(1):  # flow form on the same line
                return [
                    n.strip() for n in m.group(1).strip("[]").split(",") if n.strip()
                ]
            continue
        if inside:
            if not line.startswith((" ", "\t", "-")):
                break  # next top-level key
            if line.strip().startswith("- "):
                names.append(line.strip()[2:].strip())
    return names


def stub(name):
    """The library SKILL.md's frontmatter block, then the pointer body."""
    text = open(os.path.join(LIBRARY, name, "SKILL.md"), encoding="utf-8").read()
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    front = text[: end + 4]
    body = os.path.join(LIBRARY, name, "instructions.md")
    return (
        f"{front}\n{MARKER}\n\n"
        f"Read `{body}` and follow it.\n"
        f"Resolve `${{CLAUDE_PLUGIN_ROOT}}` as `{ROOT}`.\n"
    )


def ours(folder):
    p = os.path.join(folder, "SKILL.md")
    try:
        return MARKER in open(p, encoding="utf-8").read()
    except OSError:
        return False


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--project", default=".")
    ap.add_argument("--user", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    if a.user:
        root = os.path.expanduser("~")
        manifest = os.path.join(root, ".aai", "skills-manifest.yaml")
    else:
        root = os.path.abspath(a.project)
        manifest = os.path.join(root, "skills-manifest.yaml")

    want = enabled(manifest)
    out = {"written": [], "removed": [], "missing": [], "skipped": []}
    stubs = {}
    for name in want:
        s = os.path.isfile(os.path.join(LIBRARY, name, "SKILL.md")) and stub(name)
        if s:
            stubs[name] = s
        else:
            out["missing"].append(name)

    for t in TARGETS:
        d = os.path.join(root, t)
        for name, s in stubs.items():
            folder = os.path.join(d, name)
            path = os.path.join(folder, "SKILL.md")
            if (
                os.path.lexists(path)
                or os.path.lexists(folder)
                and not os.path.isdir(folder)
            ) and not ours(folder):
                out["skipped"].append(f"{t}/{name}")  # user's own skill or a fork
                continue
            if os.path.exists(path) and open(path, encoding="utf-8").read() == s:
                continue
            out["written"].append(f"{t}/{name}")
            if not a.dry_run:
                os.makedirs(folder, exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(s)
        if os.path.isdir(d):
            for name in sorted(os.listdir(d)):
                folder = os.path.join(d, name)
                if name not in stubs and os.path.isdir(folder) and ours(folder):
                    out["removed"].append(f"{t}/{name}")
                    if not a.dry_run:  # only our file; keep anything the user added
                        os.remove(os.path.join(folder, "SKILL.md"))
                        if not os.listdir(folder):
                            os.rmdir(folder)

    print(json.dumps(out))


if __name__ == "__main__":
    main()
